services:

  llama3.2:
    provider:
      type: model
      options:
        model: ai/llama3.2

  qwen3:
    provider:
      type: model
      options:
        model: jimclark106/qwen3:4b-F16


  all-minilm:
    provider:
      type: model
      options:
        model: jimclark106/all-minilm:23M-F16
