server:
  port: 8747

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
      # additional-paths: src/main/resources/templates
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email,profile
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'

embabel:
  security:
    enabled: false
  models:
    default-embedding-model: jimclark106/all-minilm:23M-F16

  tripper:
    word-count: 1200
    image-width: 850

    # High quality output, expensive models
    # thinker-model: claude-3-7-sonnet-latest
    # researcher-model: gpt-4.1-mini
    # writer-model: claude-3-7-sonnet-latest
    # Acceptable quality, cheaper models
    thinker-llm:
      model: gpt-4.1
    researcher-llm:
      model: gpt-4.1-mini
    writer-llm:
      model: gpt-4.1
    max-concurrency: 12

logging:
  pattern:
    console: '%clr(%d{HH:mm:ss.SSS}){faint} %clr([%t]){magenta} %clr(%-5level) %clr(%logger{0}){cyan} %clr(-){faint} %msg%n'
  level:
    com.embabel.agent.core.ActionRunner: DEBUG
    com.embabel.agent.config.models.DockerLocalModels: DEBUG
    com.embabel.agent.web.sse.SSEController: INFO
    com.embabel.agent.tools.mcp: DEBUG